import { APIEmbed } from "discord.js";

import { ChapterLimitIndicator } from "../classes/chapterLimitIndicator";
import { ScriptureDetail, TorahDetails } from "../classes/scriptureDetail";
import { ScriptureLimitIndicator } from "../classes/scriptureLimitIndicator";
import { SectionLimitIndicator } from "../classes/sectionLimitIndicator";
import { TScriptureCode } from "./types";

export function isAPIEmbed(obj: unknown): obj is APIEmbed {
  if (typeof obj !== "object" || obj === null) return false;

  const validEmbedTypes = [
    "rich",
    "image",
    "video",
    "gifv",
    "article",
    "link",
    "auto_moderation_message",
    "poll_result",
  ];

  {
    const title = Reflect.get(obj, "title");
    if (title !== undefined && typeof title !== "string") return false;

    const description = Reflect.get(obj, "description");
    if (description !== undefined && typeof description !== "string")
      return false;

    const url = Reflect.get(obj, "url");
    if (url !== undefined && typeof url !== "string") return false;

    const timestamp = Reflect.get(obj, "timestamp");
    if (timestamp !== undefined && typeof timestamp !== "string") return false;

    const color = Reflect.get(obj, "color");
    if (color !== undefined && typeof color !== "number") return false;

    const type = Reflect.get(obj, "type");
    if (type !== undefined) {
      if (typeof type !== "string" || !validEmbedTypes.includes(type)) {
        return false;
      }
    }
  }

  {
    const fields = Reflect.get(obj, "fields");
    if (fields !== undefined) {
      if (!Array.isArray(fields)) return false;
      for (const field of fields) {
        if (typeof field !== "object" || field === null) return false;

        const name = Reflect.get(field, "name");
        if (typeof name !== "string") return false;

        const value = Reflect.get(field, "value");
        if (typeof value !== "string") return false;

        const inline = Reflect.get(field, "inline");
        if (inline !== undefined && typeof inline !== "boolean") return false;
      }
    }
  }

  {
    const author = Reflect.get(obj, "author");
    if (author !== undefined) {
      if (typeof author !== "object" || author === null) return false;

      const name = Reflect.get(author, "name");
      if (typeof name !== "string") return false;

      const url = Reflect.get(author, "url");
      if (url !== undefined && typeof url !== "string") return false;

      const icon_url = Reflect.get(author, "icon_url");
      if (icon_url !== undefined && typeof icon_url !== "string") return false;

      const proxy_icon_url = Reflect.get(author, "proxy_icon_url");
      if (proxy_icon_url !== undefined && typeof proxy_icon_url !== "string")
        return false;
    }
  }

  return true;
}

export const SCRIPTURE_DATA: Record<TScriptureCode, ScriptureDetail> = {
  t: new TorahDetails(
    new ScriptureLimitIndicator([
      new SectionLimitIndicator([
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(67),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(46),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(55),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(57),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(26),
      ]),
      new SectionLimitIndicator([
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(51),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(46),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(38),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(47),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(59),
        new ChapterLimitIndicator(57),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(44),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(55),
        new ChapterLimitIndicator(46),
        new ChapterLimitIndicator(34),
      ]),
      new SectionLimitIndicator([
        new ChapterLimitIndicator(54),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(51),
        new ChapterLimitIndicator(49),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(89),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(45),
        new ChapterLimitIndicator(41),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(41),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(65),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(39),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(54),
        new ChapterLimitIndicator(42),
        new ChapterLimitIndicator(56),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(13),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(46),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(49),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(69),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(52),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(12),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(63),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(51),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(45),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(33),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(57),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(48),
        new ChapterLimitIndicator(25),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(52),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(58),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(42),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(44),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(13),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(39),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(39),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(44),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(51),
        new ChapterLimitIndicator(39),
        new ChapterLimitIndicator(25),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(53),
        new ChapterLimitIndicator(46),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(51),
        new ChapterLimitIndicator(66),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(46),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(54),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(44),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(41),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(30),
      ]),
      new SectionLimitIndicator([
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(7),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(24),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(44),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(41),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(34),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(63),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(44),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(49),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(49),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(35),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(5),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(10),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(5),
        new ChapterLimitIndicator(21),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(15),
      ]),

      new SectionLimitIndicator([new ChapterLimitIndicator(21)]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(11),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(20),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(19),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(19),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(20),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(23),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(21),
      ]),
      new SectionLimitIndicator([
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(24),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(7),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(7),
        new ChapterLimitIndicator(5),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(51),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(5),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(7),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(5),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(45),
        new ChapterLimitIndicator(48),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(7),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(2),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(176),
        new ChapterLimitIndicator(7),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(4),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(5),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(5),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(3),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(3),
        new ChapterLimitIndicator(3),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(6),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(31),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(35),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(6),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(41),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(17),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(14),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(22),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(66),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(22),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(26),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(14),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(10),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(3),
      ]),
      new SectionLimitIndicator([
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(49),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(45),
        new ChapterLimitIndicator(13),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(70),
        new ChapterLimitIndicator(13),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(15),
        new ChapterLimitIndicator(44),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(38),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(72),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(47),
        new ChapterLimitIndicator(31),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(54),
        new ChapterLimitIndicator(55),
        new ChapterLimitIndicator(24),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(41),
        new ChapterLimitIndicator(66),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(40),
        new ChapterLimitIndicator(44),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(47),
        new ChapterLimitIndicator(41),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(29),
        new ChapterLimitIndicator(43),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(8),
        new ChapterLimitIndicator(30),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(32),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(30),
      ]),

      new SectionLimitIndicator([
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(17),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(42),
        new ChapterLimitIndicator(22),
        new ChapterLimitIndicator(18),
        new ChapterLimitIndicator(31),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(16),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(14),
        new ChapterLimitIndicator(19),
        new ChapterLimitIndicator(34),
        new ChapterLimitIndicator(11),
        new ChapterLimitIndicator(37),
        new ChapterLimitIndicator(20),
        new ChapterLimitIndicator(12),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(28),
        new ChapterLimitIndicator(23),
        new ChapterLimitIndicator(9),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(36),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(21),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(25),
        new ChapterLimitIndicator(33),
        new ChapterLimitIndicator(27),
        new ChapterLimitIndicator(23),
      ]),
    ])
  ),
} as const;
